"""users table

Revision ID: 363151a4fdc3
Revises: 46297bc0034b
Create Date: 2020-12-25 17:38:20.217896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363151a4fdc3'
down_revision = '46297bc0034b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
