"""empty message

Revision ID: 6491f4a03a2d
Revises: 54a320d71214
Create Date: 2020-12-13 21:51:42.263928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6491f4a03a2d'
down_revision = '54a320d71214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AnnouncementType')
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.create_foreign_key(None, 'announcement', 'announcement_type', ['announcement_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.create_foreign_key(None, 'announcement', 'AnnouncementType', ['announcement_type'], ['id'])
    op.create_table('AnnouncementType',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('announcement_type')
    # ### end Alembic commands ###
