"""posts table

Revision ID: 75a7871ef2a9
Revises: 350f781f9577
Create Date: 2020-12-13 21:20:15.113045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a7871ef2a9'
down_revision = '350f781f9577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AnnouncementType')
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.drop_column('announcement', 'authorid')
    op.create_unique_constraint(None, 'location', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    op.add_column('announcement', sa.Column('authorid', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'announcement', 'AnnouncementType', ['announcement_type'], ['id'])
    op.create_foreign_key(None, 'announcement', 'location', ['location'], ['id'])
    op.create_foreign_key(None, 'announcement', 'user', ['authorid'], ['id'])
    op.create_table('AnnouncementType',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('announcement_type')
    # ### end Alembic commands ###
